'use strict'
module.exports = (sequelize, DataTypes) => {
  /**
   * An association between users and their (ordered) favorite contentLists
   * Favorites accepts any Array of type String so that contentLists with
   * natural blockchain ids can be stored alongside autogenerated contentLists.
   */
  const UserContentListFavorites = sequelize.define('UserContentListFavorites', {
    userId: {
      type: DataTypes.INTEGER,
      allowNull: false,
      primaryKey: true
    },
    favorites: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      allowNull: false
    },
    createdAt: {
      allowNull: false,
      type: DataTypes.DATE
    },
    updatedAt: {
      allowNull: false,
      type: DataTypes.DATE
    }
  }, {})
  return UserContentListFavorites
}
