export coliving_delegate_owner_wallet=AUDIUS_DELEGATE_OWNER_WALLET
export coliving_delegate_private_key=AUDIUS_DELEGATE_PRIVATE_KEY
echo $coliving_delegate_owner_wallet
echo $coliving_delegate_private_key
export COMPOSE_HTTP_TIMEOUT=200
export coliving_discprov_loglevel_flask=DEBUG
