"""Enable contentLists migration

Revision ID: 15c49e56770d
Revises: cc7540f26188
Create Date: 2019-02-25 09:50:51.744223

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "15c49e56770d"
down_revision = "cc7540f26188"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contentLists",
        sa.Column("blockhash", sa.String(), nullable=False),
        sa.Column("blocknumber", sa.Integer(), nullable=False),
        sa.Column("contentList_id", sa.Integer(), nullable=False),
        sa.Column("contentList_owner_id", sa.Integer(), nullable=False),
        sa.Column("is_album", sa.Boolean(), nullable=False),
        sa.Column("is_private", sa.Boolean(), nullable=False),
        sa.Column("contentList_name", sa.String(), nullable=True),
        sa.Column(
            "contentList_contents", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("contentList_image_multihash", sa.String(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("is_delete", sa.Boolean(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["blockhash"],
            ["blocks.blockhash"],
        ),
        sa.ForeignKeyConstraint(
            ["blocknumber"],
            ["blocks.number"],
        ),
        sa.PrimaryKeyConstraint(
            "is_current", "contentList_id", "contentList_owner_id", "blockhash"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contentLists")
    # ### end Alembic commands ###
