"""digital_content segments

Revision ID: 4ee3fec9c420
Revises: d4779ea63753
Create Date: 2018-12-13 18:47:57.018163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4ee3fec9c420"
down_revision = "d4779ea63753"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "digitalContents",
        sa.Column(
            "digital_content_segments", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
    )
    op.drop_column("digitalContents", "file_multihash")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "digitalContents",
        sa.Column("file_multihash", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("digitalContents", "digital_content_segments")
    # ### end Alembic commands ###
