"""add user digital_content tag mat view

Revision ID: 6d1b38f242fe
Revises: 47b07608863f
Create Date: 2020-11-23 15:57:28.424094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6d1b38f242fe"
down_revision = "47b07608863f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    connection.execute(
        """
    --- Create matviews for easier user and digital_content tag search querying
    CREATE MATERIALIZED VIEW tag_digital_content_user AS
	SELECT
        UNNEST(tags) AS tag,
        digital_content_id,
        owner_id
    FROM
    (
        SELECT
            string_to_array(LOWER(digitalContents.tags), ',') AS tags,
            digital_content_id,
            owner_id
        FROM
            digitalContents
        WHERE
            tags <> ''
            AND tags IS NOT NULL 
            AND is_current IS TRUE
            AND is_unlisted IS FALSE
            AND stem_of IS NULL
        ORDER BY
            updated_at DESC
    ) AS t
    GROUP BY
        tag,
        digital_content_id,
        owner_id;
    
    CREATE INDEX tag_digital_content_user_tag_idx ON tag_digital_content_user (tag);
    CREATE UNIQUE INDEX tag_digital_content_user_idx ON tag_digital_content_user (tag, digital_content_id, owner_id);
    """
    )


def downgrade():
    connection = op.get_bind()
    connection.execute(
        """
    DROP INDEX IF EXISTS tag_digital_content_user_tag_idx;
    DROP INDEX IF EXISTS tag_digital_content_user_idx;
    DROP MATERIALIZED VIEW tag_digital_content_user;
    """
    )
