[package]
name = "audius_eth_registry"
version = "0.1.0"
authors = [""]
edition = "2018"

[features]
no-entrypoint = []
test-bpf = []

[dependencies]
arrayref = "0.3.6"
num-derive = "0.3"
num-traits = "0.2"
num_enum = "0.5.1"
solana-program = "=1.8.14"
thiserror = "1.0"
borsh = "0.9.0"
borsh-derive = "0.9.0"

[dev-dependencies]
solana-program-test = "1.6.1"
solana-sdk = "=1.8.14"
libsecp256k1 = { version = "0.5.0" }
rand-073 = { package = "rand", version = "0.7.3" }
rand = { version = "0.8.3" }
sha3 = { version = "0.9.1" }
bincode = "1.3.3"
chrono = "0.4"

[lib]
crate-type = ["cdylib", "lib"]