version: '3'

services:
  prometheus:
    build: prometheus
    user: 0:0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9090:9090"
    restart: always
    volumes:
      - ./data/prometheus:/prometheus

  grafana:
    build:
      context: grafana
      args:
        - GRAFANA_VERSION=latest
        - GF_INSTALL_IMAGE_RENDERER_PLUGIN=true
    user: 0:0
    env_file:
      - grafana/.env
    links:
      - prometheus:prometheus
    ports:
      - "80:3000"
    restart: always
    volumes:
      - ./data/grafana:/var/lib/grafana

  # Exporters

  ## Elasticsearch Exporter

  exporter_elasticsearch_dn1:
    image: quay.io/prometheuscommunity/elasticsearch-exporter:v1.3.0
    ports:
      - "9114:9114"
    command:
      - '--es.uri=http://dn1_elasticsearch_1:9200'
    restart: always
    networks:
      - coliving_dev

  ## Postgres Exporters

  exporter_postgres_dn1:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.10.1
    ports:
      - "5010:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:postgres@dn1_discovery-node-db_1:5432/postgres?sslmode=disable
    restart: always
    networks:
      - coliving_dev

  exporter_postgres_cn1:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.10.1
    ports:
      - "4010:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:postgres@cn1_content-node-db_1:5432/postgres?sslmode=disable
    restart: always
    networks:
      - coliving_dev

  exporter_postgres_cn2:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.10.1
    ports:
      - "4011:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:postgres@cn2_content-node-db_1:5432/postgres?sslmode=disable
    restart: always
    networks:
      - coliving_dev

  exporter_postgres_cn3:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.10.1
    ports:
      - "4012:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:postgres@cn3_content-node-db_1:5432/postgres?sslmode=disable
    restart: always
    networks:
      - coliving_dev

  exporter_postgres_cn4:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.10.1
    ports:
      - "4013:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:postgres@cn4_content-node-db_1:5432/postgres?sslmode=disable
    restart: always
    networks:
      - coliving_dev

  exporter_postgres_is:
    image: quay.io/prometheuscommunity/postgres-exporter:v0.10.1
    ports:
      - "7010:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:postgres@coliving-identity-service_identity-db_1:5432/postgres?sslmode=disable
    restart: always
    networks:
      - coliving_dev

networks:
  coliving_dev:
    external: true
