{
 "title": "Coliving - Network Monitoring",
 "description": "Network-wide metrics and statuses",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"coliving_dn_flask_route_duration_seconds_count|coliving_dn_flask_route_latency_seconds_count\"}, environment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Primary Users Count by Content Node",
   "type": "piechart",
   "description": "The number of users with a specific content node as their primary",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "coliving_nm_primary_user_count{environment=~\"$env\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "All Users Count by Content Node",
   "type": "piechart",
   "description": "The number of users that have a specific content node in their replica set",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "coliving_nm_all_user_count{environment=~\"$env\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "User Status",
   "type": "bargauge",
   "description": "The number of users whose content nodes are fully synced (i.e. clock values are all the same), partially synced (i.e. clock values are same one primary and one secondary), or unsynced (i.e. the primary isn't synced with either seondary)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "coliving_nm_fully_synced_user_count{environment=~\"$env\"}",
     "legendFormat": "fully synced user count"
    },
    {
     "expr": "coliving_nm_partially_synced_user_count{environment=~\"$env\"}",
     "legendFormat": "partially synced user count"
    },
    {
     "expr": "coliving_nm_unsynced_user_count{environment=~\"$env\"}",
     "legendFormat": "unsynced user count"
    },
    {
     "expr": "coliving_nm_no_primary_user_count{environment=~\"$env\"}",
     "legendFormat": "users with null primary count"
    }
   ]
  },
  {
   "title": "User Status over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "coliving_nm_fully_synced_user_count{environment=~\"$env\"}",
     "legendFormat": "fully synced users"
    },
    {
     "expr": "coliving_nm_partially_synced_user_count{environment=~\"$env\"}",
     "legendFormat": "partially synced users"
    },
    {
     "expr": "coliving_nm_unsynced_user_count{environment=~\"$env\"}",
     "legendFormat": "unsynced users"
    },
    {
     "expr": "coliving_nm_no_primary_user_count{environment=~\"$env\"}",
     "legendFormat": "users with null primary"
    }
   ]
  },
  {
   "title": "Latest Missed Users Count by Endpoint",
   "type": "barchart",
   "description": "The number of users skipped because of network monitoring job errors",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "coliving_nm_missed_users_count{environment=~\"$env\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "User Status over Time (Dheeraj dev, do not use)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "coliving_nm_fully_synced_user_count{environment=~\"$env\"}",
     "legendFormat": "fully synced users"
    },
    {
     "expr": "coliving_nm_partially_synced_user_count{environment=~\"$env\"}",
     "legendFormat": "partially synced users"
    },
    {
     "expr": "coliving_nm_unsynced_user_count{environment=~\"$env\"}",
     "legendFormat": "unsynced users"
    },
    {
     "expr": "coliving_nm_no_primary_user_count{environment=~\"$env\"}",
     "legendFormat": "users with null primary"
    }
   ]
  },
  {
   "title": "Durations",
   "type": "barchart",
   "description": "The amount of time it takes for the various steps in a network monitoring job to finish",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "coliving_nm_total_job_duration{environment=~\"$env\"}",
     "legendFormat": "total job duration"
    },
    {
     "expr": "coliving_nm_indexing_discovery_duration{environment=~\"$env\"}",
     "legendFormat": "indexing discovery duration"
    },
    {
     "expr": "coliving_nm_indexing_content_duration{environment=~\"$env\"}",
     "legendFormat": "indexing content duration"
    },
    {
     "expr": "coliving_nm_generating_metrics_duration{environment=~\"$env\"}",
     "legendFormat": "generating metrics duration"
    }
   ]
  },
  {
   "title": "Total Missed Users by Job",
   "type": "timeseries",
   "description": "The number of users skipped because of network monitoring job errors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum by(run_id) (coliving_nm_missed_users_count{environment=~\"$env\"})",
     "legendFormat": "run {{run_id}}"
    }
   ]
  },
  {
   "title": "Avg Batch Duration",
   "type": "timeseries",
   "description": "The amount of time it takes for a batch of users to be fetched and saved to the network monitoring database",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(endpoint) (coliving_nm_user_batch_duration{environment=~\"$env\"})",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}