{
 "title": "Joaquin - Playground",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"coliving_dn_flask_route_duration_seconds_count|coliving_dn_flask_route_latency_seconds_count\"}, environment)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(coliving_dn_flask_route_duration_seconds_count{environment=~\"$env\"}, host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Panel Title", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "Celery Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Celery Tasks (Active)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "coliving_dn_celery_task_active_duration_seconds{environment=~\"$env\", host=~\"$host\"}",
       "legendFormat": "{{task_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Health Checks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Blockdiff",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "coliving_dn_health_check_block_difference_latest{environment=~\"$env\", host=~\"$host\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Latest Indexed Block",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "coliving_dn_health_check_block_difference_latest{environment=~\"$env\", host=~\"$host\"}",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Census",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Census (Population)",
     "type": "timeseries",
     "description": "[Census](https://github.com/dgc.network/load-test-tools/tree/master/census) is a load-test-tool that runs periodically to count the total number of entities that are stored at the database level.\n\nThe population panel shows the total number of entities to date.\n\nThe daily growth panel shows the growth per entity within the past ISO date.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "coliving_lt_census_population_current{environment=~\"$env\"}",
       "legendFormat": "{{entity}}"
      }
     ]
    },
    {
     "title": "Census (Today's Growth)",
     "type": "timeseries",
     "description": "[Census](https://github.com/dgc.network/load-test-tools/tree/master/census) is a load-test-tool that runs periodically to count the total number of entities that are stored at the database level.\n\nThe population panel shows the total number of entities to date.\n\nThe daily growth panel shows the growth per entity within the past ISO date.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "coliving_lt_census_growth_current{environment=~\"$env\"}",
       "legendFormat": "{{entity}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Flask Routes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Route Requests",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "max by (route) (rate(coliving_dn_flask_route_duration_seconds_count{environment=~\"$env\", host=~\"$host\"}[5m]))",
       "legendFormat": "{{host}}{{route}}"
      }
     ]
    },
    {
     "title": "Average Flask Latency",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (route) (rate(coliving_dn_flask_route_duration_seconds_sum{environment=~\"$env\", host=~\"$host\"}[5m]) / rate(coliving_dn_flask_route_duration_seconds_count{environment=~\"$env\", host=~\"$host\"}[5m]))",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Route Requests Errors",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "max by (host, route, code) (rate(coliving_dn_flask_route_duration_seconds_count{code!=\"200\", code!=\"\", environment=~\"$env\", host=~\"$host\"}[5m]))",
       "legendFormat": "{{host}}{{route}} ({{code}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Aggregate Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate Task Runs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "coliving_dn_update_aggregate_table_duration_seconds_count{environment=~\"$env\", host=~\"$host\"}",
       "legendFormat": "{{table_name}}"
      }
     ]
    },
    {
     "title": "Average Aggregate Task Runtimes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(coliving_dn_update_aggregate_table_duration_seconds_sum{environment=~\"$env\", host=~\"$host\"}[5m]) / rate(coliving_dn_update_aggregate_table_duration_seconds_count{environment=~\"$env\", host=~\"$host\"}[5m])",
       "legendFormat": "{{table_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Index Metrics Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Index Metric Runs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "coliving_dn_index_metrics_duration_seconds_count{environment=~\"$env\", host=~\"$host\"}",
       "legendFormat": "{{task_name}}"
      }
     ]
    },
    {
     "title": "Average Index Metrics Runtimes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(coliving_dn_index_metrics_duration_seconds_sum{environment=~\"$env\", host=~\"$host\"}[5m]) / rate(coliving_dn_index_metrics_duration_seconds_count{environment=~\"$env\", host=~\"$host\"}[5m])",
       "legendFormat": "{{task_name}}"
      }
     ]
    },
    {
     "title": "Average Index Block Runtimes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (scope) (rate(coliving_dn_index_blocks_duration_seconds_sum{environment=~\"$env\", host=~\"$host\"}[5m]) / rate(coliving_dn_index_blocks_duration_seconds_count{environment=~\"$env\", host=~\"$host\"}[5m]))",
       "legendFormat": "{{host}}{{scope}}"
      }
     ]
    }
   ]
  },
  {
   "title": "State Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Agreement State Runtimes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (scope) (rate(coliving_dn_agreement_state_update_duration_seconds_sum{environment=~\"$env\", host=~\"$host\"}[5m]) / rate(coliving_dn_agreement_state_update_duration_seconds_count{environment=~\"$env\", host=~\"$host\"}[5m]))",
       "legendFormat": "{{host}}{{scope}}"
      }
     ]
    },
    {
     "title": "Average User State Runtimes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (scope) (rate(coliving_dn_user_state_update_duration_seconds_sum{environment=~\"$env\", host=~\"$host\"}[5m]) / rate(coliving_dn_user_state_update_duration_seconds_count{environment=~\"$env\", host=~\"$host\"}[5m]))",
       "legendFormat": "{{host}}{{scope}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Trending Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Index Trending Runtimes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (service) (rate(coliving_dn_index_trending_duration_seconds_sum{environment=~\"$env\", host=~\"$host\"}[5m]) / rate(coliving_dn_index_trending_duration_seconds_count{environment=~\"$env\", host=~\"$host\"}[5m]))",
       "legendFormat": "index_trending_duration"
      }
     ]
    },
    {
     "title": "Average Update Trending View Runtimes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (mat_view_name) (rate(coliving_dn_update_trending_view_duration_seconds_sum{environment=~\"$env\", host=~\"$host\"}[5m]) / rate(coliving_dn_update_trending_view_duration_seconds_count{environment=~\"$env\", host=~\"$host\"}[5m]))",
       "legendFormat": "{{mat_view_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Population Script",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Population",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "coliving_loadtest_population_count{environment=~\"$env\", host=~\"$host\"}",
       "legendFormat": "{{entity}}"
      }
     ]
    },
    {
     "title": "Population Script Runtimes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, rate(coliving_loadtest_population_duration_seconds_bucket{environment=~\"$env\", host=~\"$host\"}[10m]))",
       "legendFormat": "median"
      },
      {
       "expr": "histogram_quantile(0.95, rate(coliving_loadtest_population_duration_seconds_bucket{environment=~\"$env\", host=~\"$host\"}[10m]))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, rate(coliving_loadtest_population_duration_seconds_bucket{environment=~\"$env\", host=~\"$host\"}[10m]))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.999, rate(coliving_loadtest_population_duration_seconds_bucket{environment=~\"$env\", host=~\"$host\"}[10m]))",
       "legendFormat": "p999"
      }
     ]
    }
   ]
  },
  {
   "title": "Celery Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "In Progress Runtimes",
     "type": "timeseries",
     "description": "Shows how long the longest running task (across all nodes) has been running.\n\nCurrently, metrics will not reset a stat back to 0 upon completion, so you'll see horizontal lines indicating it hasn't run since the last metric was updated.\n\nDips to 0 mean the task has started again.\n\nDips to non-0 mean that while the current task has completed, the same task was running in parallel on another node, and the metric is showing the new currently running longest task.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (task_name) (coliving_dn_celery_running_tasks{environment=~\"$env\", host=~\"$host\"})",
       "legendFormat": "{{task_name}}"
      }
     ]
    }
   ]
  }
 ]
}