{
 "title": "Joaquin - Network Monitoring v2",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"coliving_dn_flask_route_duration_seconds_count|coliving_dn_flask_route_latency_seconds_count\"}, environment)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(coliving_dn_flask_route_duration_seconds_count{environment=~\"$env\"}, host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Primary Users Count by Content Node",
   "type": "piechart",
   "description": "The number of users with a specific content node as their primary",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "primary_user_count{environment=~\"$env\", host=~\"$host\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "All Users Count by Content Node",
   "type": "piechart",
   "description": "The number of users that have a specific content node in their replica set",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "all_user_count{environment=~\"$env\", host=~\"$host\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Fully Synced User Count",
   "type": "gauge",
   "description": "The number of users whose content nodes are fully synced (i.e. clock values are all the same)",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "full_synced_user_count{environment=~\"$env\", host=~\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Primary Users Count Unbalance by Content Node",
   "type": "timeseries",
   "description": "The difference in the number of users a specific content node as their primary vs the number of users the content node with the most users has",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "primary_user_count{environment=~\"$env\", host=~\"$host\"} - on (host) group_left max by (host) (primary_user_count{environment=~\"$env\", host=~\"$host\"})",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": " All Users Count Unbalance by Content Node",
   "type": "timeseries",
   "description": "The number of users that have a specific content node in their replica set, in relation to the average number of users across all nodes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "all_user_count{environment=~\"$env\", host=~\"$host\"} - on (host) group_left avg by (host) (all_user_count{environment=~\"$env\", host=~\"$host\"})",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}