# Compose file to run the discovery backend stack (web server and celery workers)
version: '3'
services:
  web-server:
    build: ../.
    restart: always
    ports:
      - '${audius_server_port}:${audius_server_port}'
    env_file:
      - .env
    environment:
      - FLASK_RUN_PORT=${audius_server_port}
      - audius_redis_url=redis://${COMPOSE_PROJECT_NAME}_redis-server_1:6379/00
      - audius_db_url=postgresql+psycopg2://postgres:postgres@${COMPOSE_PROJECT_NAME}_discovery-provider-db_1:5432/audius_discovery
      - audius_db_url_read_replica=postgresql+psycopg2://postgres:postgres@${COMPOSE_PROJECT_NAME}_discovery-provider-db_1:5432/audius_discovery
      - audius_elasticsearch_url=http://elasticsearch:9200
      - audius_elasticsearch_run_indexer=true
      - audius_elasticsearch_search_enabled=true
      - audius_delegate_owner_wallet=${audius_delegate_owner_wallet}
      - audius_delegate_private_key=${audius_delegate_private_key}
      - audius_ipfs_host=${COMPOSE_PROJECT_NAME}-ipfs-node
      - audius_discprov_dev_mode=true
      - WAIT_HOSTS=${COMPOSE_PROJECT_NAME}_discovery-provider-db_1:5432,${COMPOSE_PROJECT_NAME}_redis-server_1:6379, ${COMPOSE_PROJECT_NAME}-ipfs-node:5001
    depends_on:
      discovery-provider-db:
        condition: service_healthy
      redis-server:
        condition: service_started
    volumes:
      - '../.:/audius-discovery-provider'
    networks:
      - audius_dev

networks:
  audius_dev:
    external: true
