# Compose file to run the discovery flask server on its own
#
# The server is pointed at whatever database is set in .env
# and runs no workers, but does need redis and IPFS to be available
version: '3'
services:
  web-server:
    build: ../.
    restart: always
    ports:
      - '${audius_server_port}:${audius_server_port}'
    env_file:
      - .env
    environment:
      - audius_db_run_migrations=false
      - FLASK_RUN_PORT=${audius_server_port}
      - audius_redis_url=redis://${COMPOSE_PROJECT_NAME}_redis-server_1:6379/00
      - audius_ipfs_host=${COMPOSE_PROJECT_NAME}-ipfs-node
      - audius_discprov_dev_mode=true
      - audius_no_workers=true
      - WAIT_HOSTS=${COMPOSE_PROJECT_NAME}_redis-server_1:6379,${COMPOSE_PROJECT_NAME}-ipfs-node:5001
    depends_on:
      - redis-server
    volumes:
      - '../.:/audius-discovery-provider'
    networks:
      - audius_dev

networks:
  audius_dev:
    external: true
