# Compose file to run just the discovery ipfs container
version: '3'
services:
  ipfs-node:
    container_name: '${COMPOSE_PROJECT_NAME}-ipfs-node'
    image: ipfs/go-ipfs:v0.8.0

    ports:
      - '${coliving_ipfs_external_port}:5001'

    networks:
      - coliving_dev

networks:
  coliving_dev:
    external: true