version: '3'
services:
  content-node-db:
    image: postgres:11.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: coliving_creator_node
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '${CREATOR_NODE_DB_HOST_PORT}:5432'
    networks:
      - coliving_dev
  content-node:
    build: ../.
    depends_on:
      - content-node-db
      - content-node-redis
    environment:
      - redisHost=${COMPOSE_PROJECT_NAME}_content-node-redis_1
      - dbUrl=postgres://postgres:postgres@${COMPOSE_PROJECT_NAME}_content-node-db_1:5432/coliving_creator_node
      - WAIT_HOSTS=${COMPOSE_PROJECT_NAME}_content-node-db_1:5432, ${COMPOSE_PROJECT_NAME}_content-node-redis_1:6379
      - port=${CREATOR_NODE_HOST_PORT}
      - debuggerPort=${CREATOR_NODE_DEBUGGER_PORT}
      - spOwnerWalletIndex=${SP_OWNER_WALLET_INDEX}
      - delegateOwnerWallet=${delegateOwnerWallet}
      - delegatePrivateKey=${delegatePrivateKey}
      - contentNodeEndpoint=${contentNodeEndpoint}
      - manualSyncsDisabled=${manualSyncsDisabled}
      - devMode=${DEV_MODE}
      - spOwnerWallet=${spOwnerWallet}
      - contentCacheLayerEnabled=${contentCacheLayerEnabled}
    env_file:
      - ./env/base.env
    ports:
      - '${CREATOR_NODE_HOST_PORT}:${CREATOR_NODE_HOST_PORT}'
      - '${CREATOR_NODE_DEBUGGER_PORT}:${CREATOR_NODE_DEBUGGER_PORT}'
    volumes:
      - ./env/tmp/file-storage-${SP_OWNER_WALLET_INDEX}:/file_storage
      - ..:/usr/src/app
      # Prevent hiding node_modules on container with host volume
      # From https://github.com/barrysteyn/node-scrypt/issues/148
      - /usr/src/app/node_modules
      # Mount coliving libs as a directory
      - ../../libs:/usr/src/coliving-libs
      # Mount solana-programs
      - ../../solana-programs:/usr/src/solana-programs
    networks:
      - coliving_dev
  content-node-redis:
    image: redis:5.0.4
    ports:
      - '${CREATOR_NODE_REDIS_HOST_PORT}:6379'
    networks:
      - coliving_dev

volumes:
  postgres_data:
  file_storage:

networks:
  coliving_dev:
    external: true
