require('./helpers')
require('./registryClientTest')
require('./userClientTest')
require('./creatorNodeTest')
require('./agreementClientTest')
require('./content listClientTest')
require('./socialFeatureClientTest')
require('./serviceTypeManagerClientTest')
require('./colivingTokenClientTest')
require('./stakingTest')
require('./providerSelectionTest')
require('./governanceTest')
require('./rewardsAttesterTest')
require('./fileHasherTest')
