# Compose file to run the discovery postres container
version: '3'
services:
  discovery-node-db:
    image: postgres:11.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: coliving_discovery
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '${coliving_db_port}:5432'
    networks:
      - coliving_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  coliving_dev:
    external: true