# Compose file to run the discovery backend stack (web server and celery workers)
version: '3'
services:
  web-server:
    build: ../.
    restart: always
    ports:
      - '${coliving_server_port}:${coliving_server_port}'
    env_file:
      - .env
    environment:
      - FLASK_RUN_PORT=${coliving_server_port}
      - coliving_redis_url=redis://${COMPOSE_PROJECT_NAME}_redis-server_1:6379/00
      - coliving_db_url=postgresql+psycopg2://postgres:postgres@${COMPOSE_PROJECT_NAME}_discovery-node-db_1:5432/coliving_discovery
      - coliving_db_url_read_replica=postgresql+psycopg2://postgres:postgres@${COMPOSE_PROJECT_NAME}_discovery-node-db_1:5432/coliving_discovery
      - coliving_elasticsearch_url=http://elasticsearch:9200
      - coliving_elasticsearch_run_indexer=true
      - coliving_elasticsearch_search_enabled=true
      - coliving_delegate_owner_wallet=${coliving_delegate_owner_wallet}
      - coliving_delegate_private_key=${coliving_delegate_private_key}
      - coliving_ipfs_host=${COMPOSE_PROJECT_NAME}-ipfs-node
      - coliving_discprov_dev_mode=true
      - WAIT_HOSTS=${COMPOSE_PROJECT_NAME}_discovery-node-db_1:5432,${COMPOSE_PROJECT_NAME}_redis-server_1:6379, ${COMPOSE_PROJECT_NAME}-ipfs-node:5001
    depends_on:
      discovery-node-db:
        condition: service_healthy
      redis-server:
        condition: service_started
    volumes:
      - '../.:/coliving-discovery-node'
    networks:
      - coliving_dev

networks:
  coliving_dev:
    external: true
