# Compose file to run the discovery redis container
version: "3"
services:
  redis-server:
    image: redis:3.0-alpine
    command: redis-server --save ''
    ports:
      - "${coliving_redis_port}:6379"
    networks:
      - coliving_dev

networks:
  coliving_dev:
    external: true
