  ###########
  # local.yml
  ###########

  #############################################
  # monitor custom exporters produced by coliving
  #############################################

  # monitor data growth using containers running colocated on prometheus-grafana-metrics

  - job_name: 'census-local'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8001']
        labels:
          host: 'host.docker.internal'
          environment: 'remote-dev'
          service: 'coliving'
          component: 'monitoring'
          job: 'census'

  ###################################################
  # monitor local (remote-dev) setups that use docker
  ###################################################

  # monitor discovery node containers

  - job_name: 'local-discovery-node'
    scheme: 'http'
    metrics_path: '/prometheus_metrics'
    static_configs:
      - targets: ['host.docker.internal:5000']
        labels:
          host: 'host.docker.internal'
          environment: 'remote-dev'
          service: 'coliving'
          component: 'discovery-node'

  # monitor content node containers

  - job_name: 'local-content-node-1'
    scheme: 'http'
    metrics_path: '/prometheus_metrics'
    static_configs:
      - targets: ['host.docker.internal:4000']
        labels:
          host: 'host.docker.internal'
          environment: 'remote-dev'
          service: 'coliving'
          component: 'content-node'

  - job_name: 'local-content-node-2'
    scheme: 'http'
    metrics_path: '/prometheus_metrics'
    static_configs:
      - targets: ['host.docker.internal:4001']
        labels:
          host: 'host.docker.internal'
          environment: 'remote-dev'
          service: 'coliving'
          component: 'content-node'

  - job_name: 'local-content-node-3'
    scheme: 'http'
    metrics_path: '/prometheus_metrics'
    static_configs:
      - targets: ['host.docker.internal:4002']
        labels:
          host: 'host.docker.internal'
          environment: 'remote-dev'
          service: 'coliving'
          component: 'content-node'

  - job_name: 'local-content-node-4'
    scheme: 'http'
    metrics_path: '/prometheus_metrics'
    static_configs:
      - targets: ['host.docker.internal:4003']
        labels:
          host: 'host.docker.internal'
          environment: 'remote-dev'
          service: 'coliving'
          component: 'content-node'

  #####################################################
  # monitor local (remote-dev) network-monitoring job
  #####################################################

  - job_name: 'local-network-monitoring'
    scheme: 'http'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:9091']
        labels:
          host: 'host.docker.internal'
          environment: 'remote-dev'
          service: 'coliving'
          component: 'network-monitoring'

  #########################################################
  # monitor third-party exporters produced by the community
  #########################################################

  # monitor elasticsearch exporter

  - job_name: 'local-exporters-elastic-dn1'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:9114']
        labels:
          host: 'host.docker.internal'
          environment: 'remote-dev'
          service: 'exporter'
          target: 'dn1'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '(.*)'
        replacement: 'es_${1}'
        target_label: __name__

  # monitor postgres exporters

  - job_name: 'local-exporters-postgres-dn1'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5010']
        labels:
          host: 'host.docker.internal'
          environment: 'remote-dev'
          service: 'exporter'
          target: 'dn1'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '(.*)'
        replacement: 'pg_${1}'
        target_label: __name__

  - job_name: 'local-exporters-postgres-cn1'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:4010']
        labels:
          host: 'host.docker.internal'
          environment: 'remote-dev'
          service: 'exporter'
          target: 'cn1'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '(.*)'
        replacement: 'pg_${1}'
        target_label: __name__

  - job_name: 'local-exporters-postgres-cn2'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:4011']
        labels:
          host: 'host.docker.internal'
          environment: 'remote-dev'
          service: 'exporter'
          target: 'cn2'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '(.*)'
        replacement: 'pg_${1}'
        target_label: __name__

  - job_name: 'local-exporters-postgres-cn3'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:4012']
        labels:
          host: 'host.docker.internal'
          environment: 'remote-dev'
          service: 'exporter'
          target: 'cn3'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '(.*)'
        replacement: 'pg_${1}'
        target_label: __name__

  - job_name: 'local-exporters-postgres-cn4'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:4013']
        labels:
          host: 'host.docker.internal'
          environment: 'remote-dev'
          service: 'exporter'
          target: 'cn4'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '(.*)'
        replacement: 'pg_${1}'
        target_label: __name__

  - job_name: 'local-exporters-postgres-is'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:7010']
        labels:
          host: 'host.docker.internal'
          environment: 'remote-dev'
          service: 'exporter'
          target: 'cn5'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '(.*)'
        replacement: 'pg_${1}'
        target_label: __name__
