  ###########
  # stage.yml
  ###########

  #############################################
  # monitor custom exporters produced by coliving
  #############################################

  # monitor data growth using containers running colocated on prometheus-grafana-metrics

  - job_name: 'census-stage'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8001']
        labels:
          host: 'host.docker.internal'
          environment: 'stage'
          service: 'coliving'
          component: 'monitoring'
          job: 'census'


  #####################################################
  # monitor stage network-monitoring job
  #####################################################

  - job_name: 'stage-network-monitoring'
    scheme: 'https'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['monitoring.staging.coliving.co']
        labels:
          host: 'monitoring.staging.coliving.co'
          environment: 'stage'
          service: 'coliving'
          component: 'network-monitoring'